https://docs.python.org/3/reference/index.html

# Numeric Type
## Integer Type
- Arbitary Precition(based by String)
- Interning(== compares values and is compares references)
  - -5 ~ 256 is cached, so reference is same
- 4 type: bin, oct, hex, dec

## Float Type
- sys.float_info
- inf + x = inf
- Coercion(Implicit Type Conversion): Integer + Float = Float

## Bool Type
- True / False
- Subclass of Integer

## Imaginary Type
- Real Part: just Integer
- Imaginary Part: Literal 'J|j'
- 3 + 4j

# String Type

## Byte String
- Use Ascii Code
- Literal b
- b'data analysis'
- Immutable bytestream

## ByteArray
- Mutable bytestream
- Not exist Literal
- bytearray(b'data analysis')

## String
- General String

# Tuple
- Literal: "," like x = 1,2 === (1,2)
- Tuple is Record so, Heterogenious Type
- Immutable Type

# List
- Mutable Object

# Ellipsis
- Used to ellipse indexing
- Used to delay implemantations
- Literal: ...

In [104]:
# Ellipsis Examples
def x():
    ...
import numpy as np
x = np.array([
    [
        [1,2,3],
        [4,5,6]
    ]
])
print(x.shape)
print(x[...])
print(x[0,...])
print(x[...,0])
print(x[...,0,:])

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]
[[1 4]]
[[1 2 3]]


# Object
- Object id is never changed
- "is" compares ids
- Object id is shown by "id(identifier)"
- Python doesn't have const variable
  - All object can be reassigned
  - Except keywords, All can be reassigned(import keyword -> keyword.kwlist)

- To show methods, dir(variable)

# Homogenious Type

- Using Coercion
- Numpy, Pandas
- Faster

# Heterogenious Type

- Not Using Coerction
- List, Array
- Slower

# Sequential Type
- List, Array
- Good to accessing

# NonSequeytial Type
- Dictionary, Set
- Use hash to be accessed
- Good to searching

# Duck-typing
- For polymorphism, Just check the interfaces, not type
- \_\_len\_\_, \_\_getitem\_\_ to be used to make an object sequential

# Mutable Type
- \_\_setitem\_\_ to be used to make an object mutable
- Without Reassigning object id, can change it's value
- Set, List, Dictionary, Kernel in tensorflow

## Operation

### Change itself and Return None
- pandas's inplace option

### Change itself and Return Value
- List's pop method

### Don't change itself and Return Value
- List's count method

# Immutable Type
- Frozenset, Tuple ..
- Mutable and Immutable types can be usually interchanged
  - Since Duck typing, nessasary interface is implementated
  - List <-> Tuple, Set <-> Frozenset
 
### dis module can be used to check register load/store

# Call Funcion
- Call by reference(Default)
- Object is passed with same object id

# Overloading

## Arithmetic Operator
- \_\_add\_\_

## Bitwise Opeartor

In [120]:
import dis

In [130]:
class A:
    def __init__(self, x):
        self.x = x
    def __add__(self, b):
        self.x = self.x + b.x
a = A(1)
b = A(2)
a + b
a.x

3