https://docs.python.org/3/reference/index.html

# Numeric Type
## Integer Type
- Arbitary Precition(based by String)
- Interning(== compares values and is compares references)
  - -5 ~ 256 is cached, so reference is same
- 4 type: bin, oct, hex, dec

## Float Type
- sys.float_info
- inf + x = inf
- Coercion(Implicit Type Conversion): Integer + Float = Float

## Bool Type
- True / False
- Subclass of Integer

## Imaginary Type
- Real Part: just Integer
- Imaginary Part: Literal 'J|j'
- 3 + 4j

# String Type

## Byte String
- Use Ascii Code
- Literal b
- b'data analysis'
- Immutable bytestream

## ByteArray
- Mutable bytestream
- Not exist Literal
- bytearray(b'data analysis')

## String
- General String

# Tuple
- Literal: "," like x = 1,2 === (1,2)
- Tuple is Record so, Heterogenious Type
- Immutable Type

# List
- Mutable Object
- \_\_\[get|set|del\]item\_\_
- Access Error: IndexError
- Error Timing
  - If OOR, immediately occurs

# Dictionary
- Literal: {}, {"a": 1}
- \_\_\[get|set|del\]item\_\_
- Access Error: KeyError
- Error Timing
  - After assigning key, error occurs
- Key type is hashable Type


# Assignment Expression
## identifier = value
- The identifier's style follows Poscal Style
- a = b = **mutable object**
  - Object id is shared
  - To assign different objects, use **copy** method

## Shallow vs Deep Copy

- import copy -> copy.deepcopy(object)

### Numpy
- The index slicing is shallow copy
- default copy method is deep copy

### Pandas
- default copy method is deep copy

## Data Analysis Basic
- Before preprocessing dataset, Must copy it

## Len technique
- To check dataset size, Use len() function

## Assignment vs Declaration vs Definition

### Assignment
- Not allocate memory

### Declaration
- Allocate memory

### Definition
- 

### Python
- Python allocate object in memory before an identifier indicates it
- So, if an identifier indicate cached memory, then usually assignment is approprate
- In the case of general objects, not integer, ..., usually declaration is approprate



In [6]:
import tensorflow as tf
print(len(tf.keras.datasets.mnist.load_data()))
x, y = tf.keras.datasets.mnist.load_data()
print(len(x), len(y))
xx, xy = x
yx, yy = y
print(len(xx), len(xy), len(yx), len(yy))

2
2 2
60000 60000 10000 10000


In [7]:
import pandas as pd
import numpy as np

a = np.array([1,2,3])
b = a[...]
c = a.copy()
print(a is b)
b[1] = 10
c[1] = 20
print(a == b)
print(a == c)

df1 = pd.DataFrame([1,2,3], columns=["a"])
df2 = df1.copy()
print(df1 is df2)
df2["a"][0] = 5
print(df1)

False
[ True  True  True]
[ True False  True]
False
   a
0  1
1  2
2  3


# Unpacking
- a, \*b = 1,2,3 # a = 1; b = \[2,3\];
- \*a, b = 1,2,3 # a = \[1,2\]; b = 3;
- a, \*b, c = 1,2,3,4,5 # a = 1; b = \[2,3,4\]; c = 5;
- \*a, = 1,2,3,4,5 # a = \[1,2,3,4,5\]
  - trailling comma must be required
  - convert tuple to list

# Ellipsis
- Used to ellipse indexing
- Used to delay implemantations
- Literal: ...

In [104]:
# Ellipsis Examples
def x():
    ...
import numpy as np
x = np.array([
    [
        [1,2,3],
        [4,5,6]
    ]
])
print(x.shape)
print(x[...])
print(x[0,...])
print(x[...,0])
print(x[...,0,:])

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]
[[1 4]]
[[1 2 3]]


# Object
- Object id is never changed
- "is" compares ids
- Object id is shown by "id(identifier)"
- Python doesn't have const variable
  - All object can be reassigned
  - Except keywords, All can be reassigned(import keyword -> keyword.kwlist)

- To show methods, dir(variable)

# Homogenious Type

- Using Coercion
- Numpy, Pandas
- Faster

# Heterogenious Type

- Not Using Coerction
- List, Array
- Slower
- Preserve member types

# Sequential Type
- \_\_len\_\_, \_\_getitem\_\_ to be used to make an object sequential
- List, Array
- Good to accessing

# NonSequeytial Type
- Dictionary, Set
- Use hash to be accessed
- Good to searching

# Duck-typing
- For polymorphism, Just check the interfaces, not type

# Inheritance-typing
- For polymorphism, inherit super class, so issubclass(me, super) is True

# Mutable Type
- \_\_setitem\_\_ to be used to make an object mutable
- Without Reassigning object id, can change it's value
- Set, List, Dictionary, Kernel in tensorflow

## Operation

### Change itself and Return None
- pandas's inplace option

### Change itself and Return Value
- List's pop method

### Don't change itself and Return Value
- List's count method

# Immutable Type
- Frozenset, Tuple ..
- Mutable and Immutable types can be usually interchanged
  - Since Duck typing, nessasary interface is implementated
  - List <-> Tuple, Set <-> Frozenset
 
### dis module can be used to check register load/store

# Hashable Type
- \_\_hash\_\_ is implemented and all elements must also hashable type
- Immutable Types are usually hashable

# Iterable Type
- \_\_iter\_\_ is implemented
  ```
  def __iter__(self):
      return iter(container)
  ```
- with \_\_next\_\_, **iter** object is automatically implemented
  ```
  class Counter:
      def __init__(self, stop):
          self.cur = 0
          self.stop = stop
      def __iter__(self):
          return self
      def __next__(self):
          if self.cur < self.stop:
              r = self.cur
              self.cur = self.cur + 1
              return r
          else:
              raise StopIteration
          
  ```

# Call Funcion
- Call by reference(Default)
- Object is passed with same object id

## Parameters vs Arguments
```
def f(x): <-- arguments
   statements
f(3) <-- parameters
```
### Arguments
```
def f(*args, **kwargs):
    pass
    
f(1,2,3, x=4, y=5,)
```
- args type is list(Variadic positional parameters)
  - All positional parameters matches args
- kwargs type is dictionary(Variadic keyword parameters)
  - All keyword parameters matches kwargs

### Positional-Only and Keyword-Only Parameters
```
def f(a,b, / , c, d, *, e, f):
    pass
f(3,4,5, 6, e=7, f=8)
```
- Before **/**, positional-only parameters
- After **\***, keyword-only parameters

### Unpacking parameters
```
def f(a,b,c):
    pass
f(*[1,2,3])
```
- if \* is used with a container in parameters, unpack container

#### Positional parameters must be before keyword parameters

## Annotation
```
def f(x:str, y:1+1, z:'hello') -> "wow":
    pass
    
f(1,2,3)
```
- def functionName(arguments\[:annotation\]) \[->annotation\]
- To use function easily, can annotate expected values
- But, it doesn't force calling function type


## Signature
- functionName(arguments\[:annotation\]) \[->annotation\]

In [71]:
def f(x:str, y:1+1, z:'hello') -> "wow":
    pass
f

<function __main__.f(x: str, y: 2, z: 'hello') -> 'wow'>

# Scope

```
# outer(), inner() 함수 입장에서 전역(global) 범위
def outer():
    # outer() 함수 입장에서 지역(local) 범위
    # inner() 함수 입장에서 비지역(nonlocal) 범위
    def inner():
        # inner 함수 입장에서 지역(local) 범위
```
- If nonlocal variables are bound a global keyword, nonlocal keyword in "inner" function raise SyntaxError

In [163]:
# Scope Error
y = 1
def f():
    global y
    y = 2
    def g():
        nonlocal y
        y = 3
    g()
f()
print(y)

SyntaxError: no binding for nonlocal 'y' found (201309035.py, line 7)

In [50]:
# Iterable Check
def x():
    for i in range(1,3):
        pass
import dis
dis.dis(x)

  3           0 LOAD_GLOBAL              0 (range)
              2 LOAD_CONST               1 (1)
              4 LOAD_CONST               2 (3)
              6 CALL_FUNCTION            2
              8 GET_ITER
        >>   10 FOR_ITER                 2 (to 16)
             12 STORE_FAST               0 (i)

  4          14 JUMP_ABSOLUTE            5 (to 10)

  3     >>   16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


# False Expression
- Integer: 0
- Float: 0.
  - Boolean is subclass of Integer. So, 0 and 0.0 are exactly same with False
  - Other objects also have False, like "", {}, but it's just semantical same expression with False
  - Thus, "" == False, {} == False, list() == False None == False are all False

# Short-Circuit Evaluation
- Doesn't evaluate remaining expression

## a && b
- Return a if a is semantical same with False, else b

## a || b
- Return b if a is semantical same with False, else a

# In Expression
- member **in** Iterable
- If **in** is used with the homogeneous objects, tested member type must be same real member type. Else, Raise TypeError
- If **in** is used with the dictionary, only compared with keys
- If **in** is used with for-in statement, access member indecated by iterable

# For Expression
``` 
for identifier in iterable:
    statements
    [break|continue]
else:
    run if statement exit normally
```
- If for statement exits by **break**, else statment doesn't run

# While Expression
```
while condition:
    statements
    [break|continue]
else:
    run if statmenet exit normally
```
- If for statement exits by **break**, else statment doesn't run

# Import System
## importlib
## pakages
### regular pakages
###  namespace pakages
## Searching
### the module caching
### finders and loaders
### import hooks
### the meta path
## Loading
### loaders
### submodules
### module spec
### import-related module attributes
### module.

# PEP8 Style Guide
https://peps.python.org/pep-0008/
## Snake Style
- Function is named by snake style
- hello_world()

## Pascal Style
- Identifiers are named by pascal style
- helloWorld

## Camel Style
- All except above are named by camel style
- HelloWorld

In [193]:
dict(a=3)

{'a': 3}